/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CafesRouteImport } from './routes/cafes'
import { Route as AtacadoRouteImport } from './routes/atacado'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesRoute = CafesRouteImport.update({
  id: '/cafes',
  path: '/cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtacadoRoute = AtacadoRouteImport.update({
  id: '/atacado',
  path: '/atacado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atacado': typeof AtacadoRoute
  '/cafes': typeof CafesRoute
  '/contato': typeof ContatoRoute
  '/historia': typeof HistoriaRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atacado': typeof AtacadoRoute
  '/cafes': typeof CafesRoute
  '/contato': typeof ContatoRoute
  '/historia': typeof HistoriaRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atacado': typeof AtacadoRoute
  '/cafes': typeof CafesRoute
  '/contato': typeof ContatoRoute
  '/historia': typeof HistoriaRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atacado'
    | '/cafes'
    | '/contato'
    | '/historia'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atacado' | '/cafes' | '/contato' | '/historia' | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/atacado'
    | '/cafes'
    | '/contato'
    | '/historia'
    | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtacadoRoute: typeof AtacadoRoute
  CafesRoute: typeof CafesRoute
  ContatoRoute: typeof ContatoRoute
  HistoriaRoute: typeof HistoriaRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atacado': {
      id: '/atacado'
      path: '/atacado'
      fullPath: '/atacado'
      preLoaderRoute: typeof AtacadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtacadoRoute: AtacadoRoute,
  CafesRoute: CafesRoute,
  ContatoRoute: ContatoRoute,
  HistoriaRoute: HistoriaRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
